version: '2'

services:
   openthread_border_router:
     build: ./openthread-otbr
     devices:
       - /dev/ttyACM0:/dev/ttyACM0
     environment:
       - RADIO_URL=""spinel+hdlc+uart:///dev/ttyACM0"
       - BACKBONE_INTERFACE="wlan0"
     sysctls:
       net.ipv6.conf.all.disable_ipv6: 0
       net.ipv4.conf.all.forwarding: 1
       net.ipv6.conf.all.forwarding: 1
     ports:
       - 80:80
     privileged: true
     labels:
       io.balena.features.kernel-modules: '1'
